# Generated by Django 3.1.3 on 2020-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajara', '0002_auto_20201115_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
